results_conn_string: ""  # TODO set Azure Storage connection string for results upload
cosmos_conn_string: ""  # TODO set Cosmos DB connection string
experiment: TravelReservation-latency
output_filename: TravelReservation-latency-5-temporal
workload: workload-5service
window: 32
num_workers: 4
num_services: 5
