apiVersion: v1
kind: ServiceAccount
metadata:
  name: pod-updater
  namespace: dse
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pod-updater
  namespace: dse
rules:
  - apiGroups: [ "" ]
    resources: [ "pods" ]
    verbs: ["get", "list", "watch", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: orleans-pod-updater
  namespace: dse
subjects:
  - kind: ServiceAccount
    name: pod-updater
    namespace: dse
roleRef:
  kind: Role
  name: orleans-pod-updater
  apiGroup: rbac.authorization.k8s.io