<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net7.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
        <ServerGarbageCollection>true</ServerGarbageCollection>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="CommandLineParser" Version="2.9.1" />
        <PackageReference Include="Google.Protobuf" Version="3.25.0"/>
        <PackageReference Include="Grpc.AspNetCore" Version="2.59.0-pre1"/>
        <PackageReference Include="Grpc.Core.Api" Version="2.62.0" />
        <PackageReference Include="Grpc.Net.Client" Version="2.59.0-pre1"/>
        <PackageReference Include="Grpc.Tools" Version="2.59.0">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\libdpr\src\FASTER.libdpr\FASTER.libdpr.csproj" />
      <ProjectReference Include="..\ExampleServices\ExampleServices.csproj" />
      <ProjectReference Include="..\FASTER.darq\FASTER.darq.csproj" />
    </ItemGroup>

    <ItemGroup>
      <Protobuf Include="twopc.proto">
        <GrpcServices>Server, Client</GrpcServices>
        <Access>Public</Access>
        <ProtoCompile>True</ProtoCompile>
        <CompileOutputs>True</CompileOutputs>
        <OutputDir>obj\Debug\net7.0\</OutputDir>
        <Generator>MSBuild:Compile</Generator>
      </Protobuf>
    <Protobuf Include="tpcc.proto">
        <GrpcServices>Server, Client</GrpcServices>
        <Access>Public</Access>
        <ProtoCompile>True</ProtoCompile>
        <CompileOutputs>True</CompileOutputs>
        <OutputDir>obj\Debug\net7.0\</OutputDir>
        <Generator>MSBuild:Compile</Generator>
    </Protobuf>
    </ItemGroup>


</Project>
