image: ""
kubectl_image: bitnami/kubectl
conn_string: foo
results_conn_string: foo
tag: default

participants:
  - num: 0
  - num: 1
  - num: 2
  - num: 3
    
speculative: false
failover: false
window: 32