<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
        <ServerGarbageCollection>true</ServerGarbageCollection>
        <OutputType>Exe</OutputType>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="Azure.Storage.Blobs" Version="12.26.0" />
      <PackageReference Include="CommandLineParser" Version="2.9.1" />
      <PackageReference Include="Microsoft.Orleans.Clustering.AzureStorage" Version="9.2.1" />
      <PackageReference Include="Microsoft.Orleans.Core" Version="9.2.1" />
      <PackageReference Include="Microsoft.Orleans.Hosting.Kubernetes" Version="9.2.1" />
      <PackageReference Include="Microsoft.Orleans.Transactions" Version="9.2.1" />
      <PackageReference Include="Microsoft.Orleans.Transactions.AzureStorage" Version="9.2.1" />
      <PackageReference Include="Orleans.Clustering.Kubernetes" Version="8.2.0" />
    </ItemGroup>

</Project>
