image: ""
kubectl_image: bitnami/kubectl
results_conn_string: foo
cosmos_conn_string: foo
experiment: TravelReservation-latency
output_filename: TravelReservation-latency-temporal
workload: workload-tiny
window: 32
num_workers: 1
num_services: 1