{{- range .Values.processors }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .name }}
  template:
    metadata:
      labels:
        app: {{ .name }}
        type: processor
    spec:
      serviceAccountName: deployment-watcher
      initContainers:
        - name: wait-pubsub
          image: {{ $.Values.kubectl_image }}
          command: [ "sh", "-c" ]
          args:
            - >
              while true; do
                notReadyCount=$(kubectl get deployment -l type=pubsub -n dse | grep -c "0/1");
                if [ "$notReadyCount" -eq 0 ]; then
                  echo "All pubsub deployments are ready.";
                  break;
                else
                  echo "Waiting for pubsub. $notReadyCount not ready.";
                  sleep 1;
                fi;
              done;
      containers:
        - command:
            - "./EventProcessing"
          args:
            - "-t"
            - "{{ .name }}"
            {{- if $.Values.processor_speculative }}
            - "-s"
            {{- end }}
            {{- if $.Values.simulated_recovery }}
            - "-r"
            {{- end }}
          image: {{ $.Values.image }}
          imagePullPolicy: IfNotPresent
          workingDir: "/app/EventProcessing/"
          name: {{ .name }}
          ports:
            - containerPort: 15721
          envFrom:
            - configMapRef:
                name: env-config
---
{{- end }}